### Variable ##########
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "region" {}
variable "bucket" {}
variable "no_of_bucket" {}
variable "vm_type" {}
#variable "availability_zone" {}
variable "subnet_id" {}